language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - npm
        - echo 'Testing!'
        - npm test:prod
    - stage: deploy
      script:
        - npm install -g firebase-tools
        - npm build
        - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master 
